### PR TITLE
feat: bake lighting into scene

### PR DESCRIPTION
**Pull request by arjunr00**
I think it looks a little better with some lighting, even though there is noise and artifacting (which can be fixed by upping the sample count before baking, but I have to study and baking slows my computer way down). Also, the baked textures make the model 22ish MB lmao oops

### CODE REVIEW

**Comment by arjunr00** [comment]
| Before | After |
| --- | --- |
| Screenshot_20201215_202946 | Screenshot_20201215_202959 |

**Comment by BryanPan342** [comment]
ITS BEAUTIFUL HOLY

**Comment by BryanPan342** [comment]
can we run baking headless?

**Comment by arjunr00** [comment]
Uhh maybe? I dunno, I had the same idea to use OCI but I think it'd be pretty hard to do since idk how to use blender headless and it was a pain in the ass to get this working through the gui lmao

**Review by BryanPan342 — APPROVED** [review]
LGTM

**Pull request merged**
